language: python

python:

  - "3.6"

install:

  - "pip3 install --upgrade pip"

  - "pip3 install jupyter"

  - "pip3 install nbconvert"

script:

  - "jupyter nbconvert --to notebook --execute 'stringExercises.ipynb'"
  - "jupyter nbconvert --to notebook --execute 'listExercises.ipynb'"
